### ISSUE TITLE
Use Temporary Free images

### ISSUE THREAD

**Issue by shaunakwyn** [shaunakwyn/Meals4US#1]
Use Temporary Free images for this type sections to make it more attractive

![image](https://user-images.githubusercontent.com/42769743/79036531-a0e0c100-7be6-11ea-91fb-998c4a09f707.png)

![image](https://user-images.githubusercontent.com/42769743/79036537-ad651980-7be6-11ea-84bd-ad794de7b213.png)

![image](https://user-images.githubusercontent.com/42769743/79036546-ba820880-7be6-11ea-8d7a-ae4a321bbfc6.png)

**Comment by Bhagyashri1992** [comment]
Done!!

![image](https://user-images.githubusercontent.com/63494135/79324998-11147d00-7f2e-11ea-8e1e-c4ff5d18c7a8.png)


![image](https://user-images.githubusercontent.com/63494135/79325119-3c976780-7f2e-11ea-8ee8-df64ac0f511f.png)
