### ISSUE TITLE
Improve UX

### ISSUE THREAD

**Issue by shaunakwyn** [shaunakwyn/Meals4US#10]
> **Improve styling for this fields for better UX.**

![image](https://user-images.githubusercontent.com/42769743/79046386-508d5180-7c2e-11ea-963b-53f7913d8b22.png)

**Comment by Bhagyashri1992** [comment]
![image](https://user-images.githubusercontent.com/63494135/79723016-b9498d80-8302-11ea-88f4-72d44dc18e19.png)

**Comment by shaunakwyn** [comment]
they have same size

![image](https://user-images.githubusercontent.com/42769743/79740238-f753ab00-831c-11ea-85b7-811f56ad5cf2.png)

apply size based on their Level


- Also this options are too large. please reduce the size of it
![image](https://user-images.githubusercontent.com/42769743/79740378-33870b80-831d-11ea-9fb4-9c21742ce259.png)

**Comment by Bhagyashri1992** [comment]
![image](https://user-images.githubusercontent.com/63494135/79778702-cd1edf00-8356-11ea-8e64-35dd1361258d.png)

**Comment by shaunakwyn** [comment]
Verified! thanks 👍
