### ISSUE TITLE
Disable email field for update profile

### ISSUE THREAD

**Issue by shaunakwyn** [shaunakwyn/Meals4US#11]
**Disable email field for update profile**

![image](https://user-images.githubusercontent.com/42769743/79046436-90543900-7c2e-11ea-8e9a-b0191e2e1267.png)

**Comment by Bhagyashri1992** [comment]
![image](https://user-images.githubusercontent.com/63494135/79342665-0ae0c980-7f4b-11ea-8b92-aea7b3e7c812.png)

**Comment by shaunakwyn** [comment]
checked ! thank you.
