### ISSUE TITLE
Delivery Radius field - content type

### ISSUE THREAD

**Issue by shaunakwyn** [shaunakwyn/Meals4US#12]
- **Delivery Radius field accepts text content also. It shouldn't**

![image](https://user-images.githubusercontent.com/42769743/79046475-d4473e00-7c2e-11ea-9e69-09a52cd1941a.png)

**Comment by Bhagyashri1992** [comment]
![image](https://user-images.githubusercontent.com/63494135/79343102-9ce8d200-7f4b-11ea-99cc-c7fe6242d5fa.png)

**Comment by shaunakwyn** [comment]
checked 👍
