### ISSUE TITLE
Google map integration - for restaurant address

### ISSUE THREAD

**Issue by shaunakwyn** [shaunakwyn/Meals4US#14]
- **Use google location search instead of this fields. we have to find nearest restaurant based on it.**

![image](https://user-images.githubusercontent.com/42769743/79046588-85e66f00-7c2f-11ea-8915-cc7231d401ab.png)

**Comment by Bhagyashri1992** [comment]
This section is changed as client said ..No map integartion is there..

**Comment by shaunakwyn** [comment]
Okay, Thank you 👍
