### ISSUE TITLE
Restaurant Photo - remove issue

### ISSUE THREAD

**Issue by shaunakwyn** [shaunakwyn/Meals4US#16]
- **it should able to remove photo**

![image](https://user-images.githubusercontent.com/42769743/79046680-0311e400-7c30-11ea-8fe0-cd827e508c24.png)

**Comment by Bhagyashri1992** [comment]
![image](https://user-images.githubusercontent.com/63494135/80754196-3f0fd900-8b4c-11ea-85f4-cd4b066ad3d7.png)

**Comment by shaunakwyn** [comment]
checked 👍
