### ISSUE TITLE
Restaurant photo field restrictions

### ISSUE THREAD

**Issue by shaunakwyn** [shaunakwyn/Meals4US#18]
- **In photos field, it shouldn't accept other doc types**

![image](https://user-images.githubusercontent.com/42769743/79046779-80d5ef80-7c30-11ea-9f6a-26b59a0f07bc.png)

**Comment by Bhagyashri1992** [comment]
![image](https://user-images.githubusercontent.com/63494135/80754335-7a120c80-8b4c-11ea-97c5-51a2810aaf4d.png)

**Comment by shaunakwyn** [comment]
checked 👍
