### ISSUE TITLE
Unique validation style

### ISSUE THREAD

**Issue by shaunakwyn** [shaunakwyn/Meals4US#2]
**Apply unique style of validation in whole website.**

![image](https://user-images.githubusercontent.com/42769743/79037032-6decfc00-7beb-11ea-94bc-41215056fd34.png)

**Comment by Bhagyashri1992** [comment]
![image](https://user-images.githubusercontent.com/63494135/79319352-d3135b00-7f25-11ea-9f91-5726c7947bec.png)
[](url)

Done ..!!

**Comment by Bhagyashri1992** [comment]
http://php.innowyn.com/meals4us/Restaurant

**Comment by shaunakwyn** [comment]
@Bhagyashri1992 

validation is not unique for email address in Restaurant Registration.

![image](https://user-images.githubusercontent.com/42769743/79346768-5ea1e180-7f50-11ea-9e58-49a2be0353e9.png)

**Comment by Bhagyashri1992** [comment]
![image](https://user-images.githubusercontent.com/63494135/79571956-b586f280-80d9-11ea-914c-cda1dfb20f61.png)

**Comment by shaunakwyn** [comment]
@Bhagyashri1992 

**I said that you have to apply uniform styling for validation for whole website.**

![image](https://user-images.githubusercontent.com/42769743/79733316-85766400-8312-11ea-9a3f-b8e7cf139ff5.png)

**Comment by Bhagyashri1992** [comment]
![image](https://user-images.githubusercontent.com/63494135/79740632-a1cbce00-831d-11ea-83a9-63ced056631c.png)

**Comment by shaunakwyn** [comment]
Verified! Thank you 👍
