### ISSUE TITLE
Flash message bug

### ISSUE THREAD

**Issue by shaunakwyn** [shaunakwyn/Meals4US#20]
**When I open Account settings it shows me this profile update message here.It shouldn't.**

> - **Also test for all flash messages**

![image](https://user-images.githubusercontent.com/42769743/79046857-e5914a00-7c30-11ea-9f38-97b6d0bef160.png)

**Comment by Bhagyashri1992** [comment]
![image](https://user-images.githubusercontent.com/63494135/79576204-8aec6800-80e0-11ea-9677-7b9e03a8c20a.png)

**Comment by shaunakwyn** [comment]
@Bhagyashri1992 
it's still not working. **please be sure when you apply "Ready for test SP" label**

![image](https://user-images.githubusercontent.com/42769743/79732448-527fa080-8311-11ea-9a45-a56d33dec855.png)


![image](https://user-images.githubusercontent.com/42769743/79732376-38de5900-8311-11ea-9f5f-094e8ee5c69a.png)

**Comment by shaunakwyn** [comment]
Verified! Thanks 👍
