### ISSUE TITLE
Flash message bug 2

### ISSUE THREAD

**Issue by shaunakwyn** [shaunakwyn/Meals4US#21]
- **Remove old flash message when new one occurs.**

![image](https://user-images.githubusercontent.com/42769743/79046909-25f0c800-7c31-11ea-82f4-5c92ad131933.png)

**Comment by Bhagyashri1992** [comment]
![image](https://user-images.githubusercontent.com/63494135/79639928-43cba900-81ac-11ea-8ade-d5b06c047f2d.png)

![image](https://user-images.githubusercontent.com/63494135/79639954-7ecddc80-81ac-11ea-8b5d-1b811341598d.png)

![image](https://user-images.githubusercontent.com/63494135/79640051-10d5e500-81ad-11ea-8ddb-1f915ad43b97.png)

**Comment by shaunakwyn** [comment]
Verified! Thank You 👍
