### ISSUE TITLE
Email Address validation in Restaurant registration

### ISSUE THREAD

**Issue by shaunakwyn** [shaunakwyn/Meals4US#22]
- it should be same length of field.
- also It should not allow user to register if email address is already exist. Or may be validation is not unique.

![image](https://user-images.githubusercontent.com/42769743/79345976-6e6cf600-7f4f-11ea-872a-d978714ef61e.png)

**Comment by Bhagyashri1992** [comment]
![image](https://user-images.githubusercontent.com/63494135/79575951-30530c00-80e0-11ea-9eae-4512ccd8e07b.png)

**Comment by shaunakwyn** [comment]
Verified! Thank you 👍

**Comment by shaunakwyn** [comment]
It shouldn't allow this type of email format ...

![image](https://user-images.githubusercontent.com/42769743/79831518-32a9b480-83c5-11ea-969f-bccbe18644f2.png)

**Comment by Bhagyashri1992** [comment]
![image](https://user-images.githubusercontent.com/63494135/80288109-58cbad80-8753-11ea-93d3-f03c8af5dd04.png)

**Comment by shaunakwyn** [comment]
Verified. thanks 👍
