### ISSUE TITLE
Apply  ( * ) sign for required fields 

### ISSUE THREAD

**Issue by shaunakwyn** [shaunakwyn/Meals4US#24]
- **Cuisine Type** this field needs to be required.
- Also apply ( * ) sign for required fields.

![image](https://user-images.githubusercontent.com/42769743/79733471-d1290d80-8312-11ea-9b40-09d323185f01.png)

**Comment by Bhagyashri1992** [comment]
![image](https://user-images.githubusercontent.com/63494135/79742945-4996cb00-8321-11ea-846f-774f690bc9ad.png)

![image](https://user-images.githubusercontent.com/63494135/79743096-9aa6bf00-8321-11ea-84d6-8047ecd5d655.png)

**Comment by Bhagyashri1992** [comment]
![image](https://user-images.githubusercontent.com/63494135/79782608-fe9aa900-835c-11ea-9af7-8795743458be.png)

**Comment by shaunakwyn** [comment]
Verified! thanks 👍
