### ISSUE TITLE
Make Business type field also required - Admin Registration

### ISSUE THREAD

**Issue by shaunakwyn** [shaunakwyn/Meals4US#25]
Make Business type field also required.

![image](https://user-images.githubusercontent.com/42769743/79734293-1b5ebe80-8314-11ea-8b8c-7daa94e9d6aa.png)

**Comment by Bhagyashri1992** [comment]
![image](https://user-images.githubusercontent.com/63494135/79782456-c004ee80-835c-11ea-9e09-34fc96a90787.png)

**Comment by shaunakwyn** [comment]
Verified! Thanks 👍
