### ISSUE TITLE
Account Settings - UI/UX

### ISSUE THREAD

**Issue by shaunakwyn** [shaunakwyn/Meals4US#26]
Why it's showing this type of effects?

![image](https://user-images.githubusercontent.com/42769743/79736790-fd935880-8317-11ea-925e-ae2929c1ffe7.png)

**Comment by shaunakwyn** [comment]
Also When I typing into a field style is changed

![image](https://user-images.githubusercontent.com/42769743/79737024-55ca5a80-8318-11ea-8d55-df669645c663.png)

**Comment by shaunakwyn** [comment]
Also for email fields 

![image](https://user-images.githubusercontent.com/42769743/79737382-dbe6a100-8318-11ea-92dd-84a0c98caf16.png)

**Comment by Bhagyashri1992** [comment]
design changes made by validate.js so i can not solve these..some classes are assign by validate.js .
i try to understand the script but not understand which script puts their classes

**Comment by shaunakwyn** [comment]
@Bhagyashri1992 
May be they provide styling options also..
So, check on it. Or you can also customise core files.

**Comment by shaunakwyn** [comment]
### think multiple validation applied on single field that's why it's comes and quick reset.
### check for that

**Comment by Bhagyashri1992** [comment]
no , i have checked it.. there is only single validation apply for the fields.. so now it can not be solved by me..it is pending..

**Comment by shaunakwyn** [comment]
checked 👍
