### ISSUE TITLE
Hide not required links

### ISSUE THREAD

**Issue by shaunakwyn** [shaunakwyn/Meals4US#27]
![image](https://user-images.githubusercontent.com/42769743/79830905-05a8d200-83c4-11ea-9f7c-83c1797b30bb.png)

![image](https://user-images.githubusercontent.com/42769743/79830933-15281b00-83c4-11ea-8fb7-d68334a6c90e.png)

**Comment by Bhagyashri1992** [comment]
![image](https://user-images.githubusercontent.com/63494135/80288031-c0352d80-8752-11ea-8f38-c02bee8b5c45.png)

![image](https://user-images.githubusercontent.com/63494135/80288039-cc20ef80-8752-11ea-88c7-4cdf0a91c8d7.png)

**Comment by shaunakwyn** [comment]
Verified 👍
