### ISSUE TITLE
item options & Item Ingredients not showing

### ISSUE THREAD

**Issue by shaunakwyn** [shaunakwyn/Meals4US#29]
no data fetch for this two

**Also when you create any module atleast you have to check once that it's working then move that to done.**

![image](https://user-images.githubusercontent.com/42769743/79833576-3c351b80-83c9-11ea-8faf-92544bb3bb45.png)

**Comment by Bhagyashri1992** [comment]
![image](https://user-images.githubusercontent.com/63494135/80316716-ff2fb580-881c-11ea-95b4-c299cd853204.png)

**Comment by shaunakwyn** [comment]
checked 👍
