### ISSUE TITLE
Password validation in Sign Up

### ISSUE THREAD

**Issue by shaunakwyn** [shaunakwyn/Meals4US#3]
**Password Not Matched still I'm able to sign up**

![image](https://user-images.githubusercontent.com/42769743/79037268-0637b080-7bed-11ea-9c0d-751681bc9a97.png)

**Comment by Bhagyashri1992** [comment]
**If password not matched not register the **restaurant****

![image](https://user-images.githubusercontent.com/63494135/79320605-b1b36e80-7f27-11ea-9fed-996821c66c27.png)

**Comment by shaunakwyn** [comment]
@Bhagyashri1992 

why it's showing multiple validation for the same?

![image](https://user-images.githubusercontent.com/42769743/79345793-31086880-7f4f-11ea-8f82-1a43df1b7df0.png)

please check..

**Comment by shaunakwyn** [comment]
@Bhagyashri1992 ,
     still it's showing on wrong place. please correct it.

![image](https://user-images.githubusercontent.com/42769743/79730800-fca9f900-830e-11ea-9aba-99cc27737f06.png)

**Comment by Bhagyashri1992** [comment]
![image](https://user-images.githubusercontent.com/63494135/79742432-726a9080-8320-11ea-96c8-ba6c7c6cce39.png)

**Comment by shaunakwyn** [comment]
@Bhagyashri1992 
show matching password validation under confirm password only.
as of now it's comes under password and confirm password both.

![image](https://user-images.githubusercontent.com/42769743/79828546-895fc000-83be-11ea-9755-4d65a4ed1a19.png)

**Comment by Bhagyashri1992** [comment]
![image](https://user-images.githubusercontent.com/63494135/80377111-71090d00-88b8-11ea-8ba3-ba1f188aee37.png)

under password msg shows just suggestion about strong password,..

**Comment by shaunakwyn** [comment]
checked 👍
