### ISSUE TITLE
Put Toggle switch instead of radio buttons

### ISSUE THREAD

**Issue by shaunakwyn** [shaunakwyn/Meals4US#34]
![image](https://user-images.githubusercontent.com/42769743/79837027-794fdc80-83ce-11ea-8804-0ffc2f34a1ff.png)

**Comment by Bhagyashri1992** [comment]
![image](https://user-images.githubusercontent.com/63494135/80516297-e2bc8600-89a0-11ea-843e-cd1f4411e1a3.png)

**Comment by shaunakwyn** [comment]
checked 👍
