### ISSUE TITLE
Not shown in some cases in order list

### ISSUE THREAD

**Issue by shaunakwyn** [shaunakwyn/Meals4US#38]
Not able to see my order in order list...

![image](https://user-images.githubusercontent.com/42769743/79858581-46691100-83ed-11ea-8202-73909d6db564.png)

**Comment by shaunakwyn** [comment]
### It's showing none in cancelled status as there are 3 canceled orders

![image](https://user-images.githubusercontent.com/42769743/80365840-db648200-88a5-11ea-9a38-eeb227055c9d.png)

**Comment by Bhagyashri1992** [comment]
![image](https://user-images.githubusercontent.com/63494135/80522873-d76e5800-89aa-11ea-812b-3adc4c0a5626.png)

**Comment by shaunakwyn** [comment]
### only first time it's works but when you change multiples time for testing it's stopped working.

![image](https://user-images.githubusercontent.com/42769743/80698709-7eacd580-8af8-11ea-9521-44f5925252e1.png)

**Comment by shaunakwyn** [comment]
checked 👍
