### ISSUE TITLE
Preloader on sorting request - Order Approval 

### ISSUE THREAD

**Issue by shaunakwyn** [shaunakwyn/Meals4US#39]
when I apply sorting show preloader on request to prevent multiple request at a time.

![image](https://user-images.githubusercontent.com/42769743/79858802-98119b80-83ed-11ea-8868-daafc1946ad6.png)

**Comment by Bhagyashri1992** [comment]
![image](https://user-images.githubusercontent.com/63494135/80523335-87dc5c00-89ab-11ea-9f66-2680d93b56f1.png)

**Comment by shaunakwyn** [comment]
checked 👍
