### ISSUE TITLE
Login form action/events/activities

### ISSUE THREAD

**Issue by shaunakwyn** [shaunakwyn/Meals4US#4]
- I login at restaurant side but didn't find any successfully logged message.it show me restaurant login. 
- No message shown for invalid login deatils
- also nothing change in menu options. 
- differentiate Homepage for logged in and non logged in users & hide unnecessary menu option if I login as a restaurant owner.
![image](https://user-images.githubusercontent.com/42769743/79037390-20be5980-7bee-11ea-8f7e-dbd0ee513f91.png)

**Comment by Bhagyashri1992** [comment]
**Error msg show after invalid credentials provide  in login**

![image](https://user-images.githubusercontent.com/63494135/79320205-0b676900-7f27-11ea-91ab-40748fabb1ae.png)

**After right credentials are provided then redirect to admin panel** 

![image](https://user-images.githubusercontent.com/63494135/79320409-6c8f3c80-7f27-11ea-860d-ef0738fdb7ab.png)

![image](https://user-images.githubusercontent.com/63494135/79320472-80d33980-7f27-11ea-8dbe-67a24d63fed0.png)

**Comment by shaunakwyn** [comment]
Verified! thanks 👍
