### ISSUE TITLE
Prevent ordering for empty cart

### ISSUE THREAD

**Issue by shaunakwyn** [shaunakwyn/Meals4US#41]
![image](https://user-images.githubusercontent.com/42769743/79859538-c5127e00-83ee-11ea-99ba-0b89b7af5115.png)

**Comment by shaunakwyn** [comment]
it's shows this type of notice 

![image](https://user-images.githubusercontent.com/42769743/79859613-e8d5c400-83ee-11ea-9862-f3f6d433c424.png)

**Comment by Bhagyashri1992** [comment]
![image](https://user-images.githubusercontent.com/63494135/80315845-da850f00-8817-11ea-82fe-4018db67850e.png)

**Comment by shaunakwyn** [comment]
checked 👍
