### ISSUE TITLE
Prevent to choosing multiple delivery methods

### ISSUE THREAD

**Issue by shaunakwyn** [shaunakwyn/Meals4US#42]
on front side in order flow it shouldn't allowed multiple delivery methods

![image](https://user-images.githubusercontent.com/42769743/79859912-68639300-83ef-11ea-9810-794c3409bb15.png)

**Comment by Bhagyashri1992** [comment]
![image](https://user-images.githubusercontent.com/63494135/80316225-0e613400-881a-11ea-8190-4c006a7c1900.png)

**Comment by shaunakwyn** [comment]
checked 👍
