### ISSUE TITLE
Missing item options & item ingredients data

### ISSUE THREAD

**Issue by shaunakwyn** [shaunakwyn/Meals4US#43]
I already add data for item options and item ingredients. but it's not showing here also...

![image](https://user-images.githubusercontent.com/42769743/79860423-46b6db80-83f0-11ea-8865-f981b5440f5c.png)

**Comment by Bhagyashri1992** [comment]
![image](https://user-images.githubusercontent.com/63494135/80316142-b9252280-8819-11ea-8b34-d3d4cec5cda7.png)

**Comment by shaunakwyn** [comment]
checked 👍
