### ISSUE TITLE
Validation - Order Details

### ISSUE THREAD

**Issue by shaunakwyn** [shaunakwyn/Meals4US#44]
Provide validation in order details form 

![image](https://user-images.githubusercontent.com/42769743/79862849-589a7d80-83f4-11ea-9abe-a0b49d5cebf5.png)

**Comment by Bhagyashri1992** [comment]
![image](https://user-images.githubusercontent.com/63494135/80315878-11f3bb80-8818-11ea-9418-037a95227ec6.png)

**Comment by shaunakwyn** [comment]
checked 👍
