### ISSUE TITLE
Duplicate on Approval 

### ISSUE THREAD

**Issue by shaunakwyn** [shaunakwyn/Meals4US#47]
When I approve order then it's duplicate it's self and now there 4 orders instead of 2

![image](https://user-images.githubusercontent.com/42769743/79863651-bed3d000-83f5-11ea-8ac4-16356fd8bf4d.png)

**Comment by Bhagyashri1992** [comment]
![image](https://user-images.githubusercontent.com/63494135/80288366-3175e000-8755-11ea-8935-9d5771a75321.png)

**Comment by shaunakwyn** [comment]
its working right now
