### ISSUE TITLE
Approval Prevention 

### ISSUE THREAD

**Issue by shaunakwyn** [shaunakwyn/Meals4US#48]
its's allowing to approve order again. it shouldn't.
same for canceling again 
![image](https://user-images.githubusercontent.com/42769743/79864100-7bc62c80-83f6-11ea-8cc5-91b00409137f.png)

**Comment by Bhagyashri1992** [comment]
![image](https://user-images.githubusercontent.com/63494135/80288356-202cd380-8755-11ea-895c-cb49875d7f6f.png)

**Comment by shaunakwyn** [comment]
I think you not understood this  issue but it's okay we can fix this later...
