### ISSUE TITLE
Cancel button for Activity

### ISSUE THREAD

**Issue by shaunakwyn** [shaunakwyn/Meals4US#49]
**Give cancel option wherever required in system...**

![image](https://user-images.githubusercontent.com/42769743/80302348-23f93e00-87c7-11ea-843f-90121fbf6f61.png)

**Comment by Bhagyashri1992** [comment]
![image](https://user-images.githubusercontent.com/63494135/80315932-731b8f00-8818-11ea-9f8a-b5f8fc6676f6.png)

**Comment by shaunakwyn** [comment]
checked 👍
