### ISSUE TITLE
Forgot Password - Blank Page

### ISSUE THREAD

**Issue by shaunakwyn** [shaunakwyn/Meals4US#5]
**After form submited it's redirect me to blank page**

![image](https://user-images.githubusercontent.com/42769743/79046112-7d406980-7c2c-11ea-8011-3f2615bef9be.png)

**Comment by Bhagyashri1992** [comment]
Done !!

I have provide valid registered email then it redirects to reset password form 

![image](https://user-images.githubusercontent.com/63494135/79321068-6c437100-7f28-11ea-943e-140a72dd82e1.png)

**Comment by shaunakwyn** [comment]
@Bhagyashri1992 

Please apply same style to this validation also

![image](https://user-images.githubusercontent.com/42769743/79346997-b3455c80-7f50-11ea-9ee3-b6fc0ebd845c.png)

**Comment by shaunakwyn** [comment]
@Bhagyashri1992 
Also I just register in Restaurant with my email id but still it says that it's not register

![image](https://user-images.githubusercontent.com/42769743/79347417-4f6f6380-7f51-11ea-95fb-99aeecfd2a51.png)

**Comment by shaunakwyn** [comment]
@Bhagyashri1992 
Not able to check because of https://github.com/shaunakwyn/Meals4US/issues/6#issuecomment-614066746

**Comment by Bhagyashri1992** [comment]
![image](https://user-images.githubusercontent.com/63494135/79573263-fb44ba80-80db-11ea-939b-8f65d2e98501.png)

![image](https://user-images.githubusercontent.com/63494135/79573297-0c8dc700-80dc-11ea-855d-d77a84b694ca.png)

**Comment by shaunakwyn** [comment]
@Bhagyashri1992 
Not able to check because of this issue https://github.com/shaunakwyn/Meals4US/issues/6#issuecomment-616439405

**Comment by Bhagyashri1992** [comment]
![image](https://user-images.githubusercontent.com/63494135/79776876-0570ee00-8354-11ea-967f-d3196e196433.png)

**Comment by shaunakwyn** [comment]
checked 👍
