### ISSUE TITLE
Remove item Ingredients

### ISSUE THREAD

**Issue by shaunakwyn** [shaunakwyn/Meals4US#50]
**I'm not able to remove item Ingredients by client this cross button**

![image](https://user-images.githubusercontent.com/42769743/80302442-b3065600-87c7-11ea-882d-49e315711414.png)

**Comment by shaunakwyn** [comment]
I removed this but when come back it's still there

![image](https://user-images.githubusercontent.com/42769743/80365421-3053c880-88a5-11ea-9570-b4c607bbc1b7.png)

**Comment by shaunakwyn** [comment]
Also When I remove all and add new item ingredients then it's add only cross button

![image](https://user-images.githubusercontent.com/42769743/80365526-5f6a3a00-88a5-11ea-8e9f-ce623fe3b7ac.png)

**Comment by Bhagyashri1992** [comment]
when you click the cross button then again submit the page or not?

**Comment by shaunakwyn** [comment]
### yes I'm following proper way and steps

**Comment by shaunakwyn** [comment]
### when I remove this field it's automatically submit or refresh that page

![image](https://user-images.githubusercontent.com/42769743/80857199-e33d7100-8c6d-11ea-9736-8687b64e52cd.png)

**Comment by Bhagyashri1992** [comment]
when you click the cross , item option or ingrediant removes / delete from database so page has to be refreshed../submited

**Comment by shaunakwyn** [comment]
as of now we consider it as a completed 👍
