### ISSUE TITLE
Prevent empty data

### ISSUE THREAD

**Issue by shaunakwyn** [shaunakwyn/Meals4US#51]
**Prevent submitting an empty data in database...**

![image](https://user-images.githubusercontent.com/42769743/80302501-14c6c000-87c8-11ea-9636-c8f74738ada8.png)

**Comment by Bhagyashri1992** [comment]
![image](https://user-images.githubusercontent.com/63494135/80316180-d823b480-8819-11ea-9dad-ba6eea5f02fd.png)

**Comment by shaunakwyn** [comment]
checked 👍
