### ISSUE TITLE
Empty Cart

### ISSUE THREAD

**Issue by shaunakwyn** [shaunakwyn/Meals4US#52]
**when I click on order and customer details page opens then at that page my cart is empty**

![image](https://user-images.githubusercontent.com/42769743/80363950-a30f7480-88a2-11ea-81d3-c953098a9f8f.png)

**And because of this on checkout there is a blank page comes**
![image](https://user-images.githubusercontent.com/42769743/80364190-1a450880-88a3-11ea-9221-763023bd9b7b.png)

**Comment by Bhagyashri1992** [comment]
yes I know that it is under progress .. so

**Comment by Bhagyashri1992** [comment]
![image](https://user-images.githubusercontent.com/63494135/80924290-be4c1980-8da5-11ea-8c7b-8d2b5bcb8392.png)

**Comment by Bhagyashri1992** [comment]
![image](https://user-images.githubusercontent.com/63494135/80924757-77abee80-8da8-11ea-81a8-c292f87f20b1.png)

**Comment by shaunakwyn** [comment]
checked 👍
