### ISSUE TITLE
Placeholder not matched

### ISSUE THREAD

**Issue by shaunakwyn** [shaunakwyn/Meals4US#54]
**Place holder not matched as purpose**

![image](https://user-images.githubusercontent.com/42769743/80365204-d7843000-88a4-11ea-8612-f77f3226e7f4.png)

**Comment by Bhagyashri1992** [comment]
this place holder contains some example so i aonly add e.g in place holder so user can understand which type of data provide there.

**Comment by Bhagyashri1992** [comment]
![image](https://user-images.githubusercontent.com/63494135/80374405-3dc47f00-88b4-11ea-9aff-817e7ed87c23.png)

**Comment by shaunakwyn** [comment]
### Also add placeholder in newly created fields

![image](https://user-images.githubusercontent.com/42769743/80470249-5b9aee00-895f-11ea-8820-3e07baed1578.png)

**Comment by shaunakwyn** [comment]
### you set for new fields but what about old fields 
![image](https://user-images.githubusercontent.com/42769743/80807004-b17aca80-8bd9-11ea-891a-67181ed03ebe.png)

**Comment by Bhagyashri1992** [comment]
![image](https://user-images.githubusercontent.com/63494135/80831269-1baa6400-8c08-11ea-8560-0356a053c559.png)

**Comment by shaunakwyn** [comment]
### when you create that fields for stored data in database when you going to edit any item 

![image](https://user-images.githubusercontent.com/42769743/80857137-4549a680-8c6d-11ea-8bc4-5319b638c91b.png)

**Comment by shaunakwyn** [comment]
checked 👍
