### ISSUE TITLE
filled value in field 

### ISSUE THREAD

**Issue by shaunakwyn** [shaunakwyn/Meals4US#58]
### "Account Holder Type" is not getting value from database and shows selected value in it.

![image](https://user-images.githubusercontent.com/42769743/80696634-49eb4f00-8af5-11ea-9442-1849f4070a15.png)

**Comment by Bhagyashri1992** [comment]
![image](https://user-images.githubusercontent.com/63494135/80748637-dcfea600-8b42-11ea-8061-4c9a7a5b704d.png)

**Comment by shaunakwyn** [comment]
checked 👍
