### ISSUE TITLE
forgot password - email address validation

### ISSUE THREAD

**Issue by shaunakwyn** [shaunakwyn/Meals4US#6]
**Apply validation that entered email address is registered with system or not. Then send password reset link.**

**Comment by Bhagyashri1992** [comment]
Done !!


![image](https://user-images.githubusercontent.com/63494135/79320780-f7703700-7f27-11ea-985c-c3400821b1d6.png)

**Comment by shaunakwyn** [comment]
@Bhagyashri1992 

Please apply same style to this validation also

![image](https://user-images.githubusercontent.com/42769743/79346997-b3455c80-7f50-11ea-9ee3-b6fc0ebd845c.png)

**Comment by shaunakwyn** [comment]
@Bhagyashri1992 
Also I just register in Restaurant with my email id but still it says that it's not register

![image](https://user-images.githubusercontent.com/42769743/79347417-4f6f6380-7f51-11ea-95fb-99aeecfd2a51.png)

**Comment by Bhagyashri1992** [comment]
Done!!

**Comment by shaunakwyn** [comment]
@Bhagyashri1992 

it's showing me this error message

![image](https://user-images.githubusercontent.com/42769743/79738733-c83c3a00-831a-11ea-8020-c1be3627a0ef.png)

**Comment by Bhagyashri1992** [comment]
![image](https://user-images.githubusercontent.com/63494135/79776920-17eb2780-8354-11ea-92a5-728deae62e7b.png)

**Comment by shaunakwyn** [comment]
@Bhagyashri1992 
it's shows me email sent confirmation in blank page

![image](https://user-images.githubusercontent.com/42769743/79829031-b2cd1b80-83bf-11ea-96ae-41b9d1862d2e.png)

**Comment by shaunakwyn** [comment]
### put preloader on request of mail...

**Comment by shaunakwyn** [comment]
### I'm not able to get recover link for forgot password in mail. mail not received.

**Comment by shaunakwyn** [comment]
### set email output

![image](https://user-images.githubusercontent.com/42769743/80856790-9efca180-8c6a-11ea-95b5-faa5d3b17e83.png)

**Comment by Bhagyashri1992** [comment]
![image](https://user-images.githubusercontent.com/63494135/80908119-ddfa2800-8d3a-11ea-9fff-68b37d8843ab.png)

**Comment by shaunakwyn** [comment]
### it's not valid email address still going for checking in database that it's exist or not

![image](https://user-images.githubusercontent.com/42769743/80951951-76b1a600-8e16-11ea-81ed-c14386ad0a4a.png)

**Comment by shaunakwyn** [comment]
### Also on enter after entering  email address it's redirecting to below page

![image](https://user-images.githubusercontent.com/42769743/80954107-5c79c700-8e1a-11ea-9966-04eae87c5871.png)

**Comment by Bhagyashri1992** [comment]
![image](https://user-images.githubusercontent.com/63494135/81055755-fc9d2200-8ee6-11ea-9718-a06d7ee00af6.png)

**Comment by Bhagyashri1992** [comment]
![image](https://user-images.githubusercontent.com/63494135/81055855-2bb39380-8ee7-11ea-85b2-dc6d17eb646c.png)

**Comment by shaunakwyn** [comment]
### check validation for confirm password i set 2 diff and still it allowed me to update

![image](https://user-images.githubusercontent.com/42769743/81067230-f82f3400-8efb-11ea-812d-f23414eb516a.png)

**Comment by Bhagyashri1992** [comment]
![image](https://user-images.githubusercontent.com/63494135/81069546-a9839900-8eff-11ea-8e19-ca13f3811c08.png)

**Comment by shaunakwyn** [comment]
checked 👍
