### ISSUE TITLE
Images not shown

### ISSUE THREAD

**Issue by shaunakwyn** [shaunakwyn/Meals4US#60]
### uploaded images not shown here

![image](https://user-images.githubusercontent.com/42769743/80804991-68744780-8bd4-11ea-9e97-7119eed6b0d9.png)

**Comment by Bhagyashri1992** [comment]
![image](https://user-images.githubusercontent.com/63494135/80808108-6f06bd00-8bdc-11ea-9cf9-218ece88882c.png)

**Comment by shaunakwyn** [comment]
### can you make red background and tiny small ?

![image](https://user-images.githubusercontent.com/42769743/80857036-87beb380-8c6c-11ea-9b47-b09c80b6823f.png)

**Comment by Bhagyashri1992** [comment]
![image](https://user-images.githubusercontent.com/63494135/80857952-a8d6d280-8c73-11ea-883d-f64abd05d51c.png)

**Comment by shaunakwyn** [comment]
### remove has link from button as on click it brings us to top.

![image](https://user-images.githubusercontent.com/42769743/80950506-a01d0280-8e13-11ea-8167-3647b8a65ece.png)

**Comment by Bhagyashri1992** [comment]
on click of remove , image is deleted/ removed.. so only i add confirmation alert before delted.

**Comment by Bhagyashri1992** [comment]
![image](https://user-images.githubusercontent.com/63494135/81058082-569fe680-8eeb-11ea-8eb1-cd40936bd8f3.png)

**Comment by shaunakwyn** [comment]
checked 👍
