### ISSUE TITLE
Image Hover issue

### ISSUE THREAD

**Issue by shaunakwyn** [shaunakwyn/Meals4US#62]
### showing same like in profile settings https://github.com/shaunakwyn/Meals4US/issues/15

![image](https://user-images.githubusercontent.com/42769743/80807173-17ffe880-8bda-11ea-83cd-3ad745fec974.png)

**Comment by shaunakwyn** [comment]
### and also image not uploaded

**Comment by Bhagyashri1992** [comment]
![image](https://user-images.githubusercontent.com/63494135/80815853-00c9f680-8bec-11ea-98b9-e0b514f86565.png)

**Comment by Bhagyashri1992** [comment]
![image](https://user-images.githubusercontent.com/63494135/80827241-3decb380-8c01-11ea-9959-da81bd34f1b7.png)

**Comment by shaunakwyn** [comment]
### it's showing some unknown type of html in error on hover

![image](https://user-images.githubusercontent.com/42769743/80856845-15999f00-8c6b-11ea-8d0b-5d170a05731d.png)

**Comment by shaunakwyn** [comment]
### and it's not necessary to give this much big drop box for single image upload make it small

![image](https://user-images.githubusercontent.com/42769743/80856918-b720f080-8c6b-11ea-88a8-ee0c5ef6e1e2.png)

**Comment by Bhagyashri1992** [comment]
![image](https://user-images.githubusercontent.com/63494135/80857972-dd4a8e80-8c73-11ea-9a15-8934ab44cfc9.png)

**Comment by shaunakwyn** [comment]
checked 👍
