### ISSUE TITLE
Coupon Option

### ISSUE THREAD

**Issue by shaunakwyn** [shaunakwyn/Meals4US#65]
### Add this as client's requirement

![image](https://user-images.githubusercontent.com/42769743/80954489-1a04ba00-8e1b-11ea-81ec-a9cf708fb6cb.png)

**Comment by Bhagyashri1992** [comment]
![image](https://user-images.githubusercontent.com/63494135/81062905-7982c880-8ef4-11ea-8c57-bcc60b965048.png)

**Comment by shaunakwyn** [comment]
### checked ==> below field enable
### unchecked ==> below field disable
![image](https://user-images.githubusercontent.com/42769743/81066123-40e5ed80-8efa-11ea-9dfe-74844910567c.png)

**Comment by Bhagyashri1992** [comment]
![image](https://user-images.githubusercontent.com/63494135/81090817-ea89a680-8f1b-11ea-8fb2-f62fb131d01a.png)

![image](https://user-images.githubusercontent.com/63494135/81090843-f5443b80-8f1b-11ea-855c-9668f44d10c8.png)

**Comment by shaunakwyn** [comment]
checked 👍
