### ISSUE TITLE
Item image

### ISSUE THREAD

**Issue by shaunakwyn** [shaunakwyn/Meals4US#67]
### make item image required field

![image](https://user-images.githubusercontent.com/42769743/80955151-5dabf380-8e1c-11ea-8c9b-1685dec9f62c.png)

**Comment by Bhagyashri1992** [comment]
![image](https://user-images.githubusercontent.com/63494135/81218932-9e626300-8ffc-11ea-8dc6-4f655f66bc69.png)

![image](https://user-images.githubusercontent.com/63494135/81219048-cbaf1100-8ffc-11ea-8322-fc31e2005cc6.png)

![image](https://user-images.githubusercontent.com/63494135/81219073-d5d10f80-8ffc-11ea-9d0a-d19e94bbb973.png)

**Comment by Bhagyashri1992** [comment]
![image](https://user-images.githubusercontent.com/63494135/81264129-86bbc680-905e-11ea-8f47-2cc98c8cc8da.png)

![image](https://user-images.githubusercontent.com/63494135/81264475-16fa0b80-905f-11ea-9676-c8eea518d381.png)

![image](https://user-images.githubusercontent.com/63494135/81264511-2711eb00-905f-11ea-8075-934083ac5dea.png)

**Comment by shaunakwyn** [comment]
#### apply some label here

![image](https://user-images.githubusercontent.com/42769743/81279638-0785bd00-9075-11ea-8655-c6606205ef34.png)

**Comment by shaunakwyn** [comment]
checked 👍
