### ISSUE TITLE
Category Change option in item edit

### ISSUE THREAD

**Issue by shaunakwyn** [shaunakwyn/Meals4US#68]
### Category Change option in item edit

![image](https://user-images.githubusercontent.com/42769743/80955255-9a77ea80-8e1c-11ea-9401-79ddeee43f6d.png)

**Comment by Bhagyashri1992** [comment]
![image](https://user-images.githubusercontent.com/63494135/81061611-48a19400-8ef2-11ea-8dba-04610876402a.png)

**Comment by shaunakwyn** [comment]
### apply required for this field

![image](https://user-images.githubusercontent.com/42769743/81064405-4857c780-8ef7-11ea-9071-a0589d548eaf.png)

**Comment by shaunakwyn** [comment]
checked 👍
