### ISSUE TITLE
Space between sidebar & navbar

### ISSUE THREAD

**Issue by shaunakwyn** [shaunakwyn/Meals4US#7]
**There is a space in sidebar panel.**

![image](https://user-images.githubusercontent.com/42769743/79046216-2ab37d00-7c2d-11ea-9201-9fafb2b34ad7.png)

**Comment by Bhagyashri1992** [comment]
**when We put logo image then this space automatically removed..so tempaorary i have put theme logo** 

![image](https://user-images.githubusercontent.com/63494135/79337939-0fee4a80-7f44-11ea-954c-eb7ff7a8dc86.png)

**Comment by shaunakwyn** [comment]
okay @Bhagyashri1992 👍
