### ISSUE TITLE
Profile Pic upload field not there

### ISSUE THREAD

**Issue by shaunakwyn** [shaunakwyn/Meals4US#8]
**Not able to see any field to upload my photo in profile**

![image](https://user-images.githubusercontent.com/42769743/79046308-ce049200-7c2d-11ea-90e1-45474ab934ca.png)

**Comment by Bhagyashri1992** [comment]
**I have completely change the design of this form**

![image](https://user-images.githubusercontent.com/63494135/79341782-ef28f380-7f49-11ea-89e1-cb06ada02ff5.png)

![image](https://user-images.githubusercontent.com/63494135/79341828-01a32d00-7f4a-11ea-93ab-025148e45396.png)

![image](https://user-images.githubusercontent.com/63494135/79341869-0ec01c00-7f4a-11ea-8b9c-dbe71ccbcb63.png)

**Comment by shaunakwyn** [comment]
How can I remove upload photo 

![image](https://user-images.githubusercontent.com/42769743/79349424-d32a4f80-7f53-11ea-9008-23670a7dd261.png)

**Comment by Bhagyashri1992** [comment]
![image](https://user-images.githubusercontent.com/63494135/79604668-221ae500-810c-11ea-9a19-f36bb11024aa.png)

**Comment by shaunakwyn** [comment]
@Bhagyashri1992 

Why it's showing double tick marks and unwanted spaces

![image](https://user-images.githubusercontent.com/42769743/79739612-0c7c0a00-831c-11ea-991c-27cb357435d1.png)

**Comment by shaunakwyn** [comment]
change icon of images

![image](https://user-images.githubusercontent.com/42769743/79740096-beb3d180-831c-11ea-8628-dedea482212f.png)

**Comment by Bhagyashri1992** [comment]
![image](https://user-images.githubusercontent.com/63494135/79782184-4d940e80-835c-11ea-966c-e0aca89b83ce.png)

**Comment by Bhagyashri1992** [comment]
![image](https://user-images.githubusercontent.com/63494135/80753782-79c54180-8b4b-11ea-8025-4e605fa34714.png)

![image](https://user-images.githubusercontent.com/63494135/80753892-b09b5780-8b4b-11ea-9304-e0e66aee5182.png)

**Comment by shaunakwyn** [comment]
checked 👍
