### ISSUE TITLE
Show active link

### ISSUE THREAD

**Issue by shaunakwyn** [shaunakwyn/Meals4US#9]
**Show active tabs/panel/page**

![image](https://user-images.githubusercontent.com/42769743/79046348-099f5c00-7c2e-11ea-8499-55ff5126793a.png)

**Comment by Bhagyashri1992** [comment]
Please This can not solved by me please provide some help, i put some scipt 
$(".nav-item a.nav-link").on("click", function(){
                $(".nav-item").find(".active").removeClass("active");
               $(this).parent().addClass("active");
            });
,but it's not working

**Comment by Bhagyashri1992** [comment]
![image](https://user-images.githubusercontent.com/63494135/80491305-281c8b80-8980-11ea-9744-550fef20ac66.png)

**Comment by shaunakwyn** [comment]
checked 👍
